version: '2'
services:
  postgres_host:
    image: postgres:10-alpine
    restart: always
    ports: ["5433:5432"]
    container_name: postgres_host
    networks:
      aviation_network:
        aliases:
          - postgres_host
    volumes:
      - "${SOURCE_DATA}/pg_data:/var/lib/postgresql/data"
  redis_host:
    image: redis:3.2-alpine
    restart: always
    ports: ["6380:6379"]
    container_name: redis_host
    networks:
      aviation_network:
        aliases:
          - redis_host
  mongo_host:
    image: mongo:4.1.6
    restart: always
    ports: ["27018:27017"]
    container_name: mongo_host
    networks:
      aviation_network:
        aliases:
          - mongo_host
  service-app:
    build:
      context: ./data_client
    depends_on:
      - postgres_host
      - redis_host
      - mongo_host
    environment:
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
      - APP_POSTGRES_USER=postgres
      - APP_REDIS_HOST=redis_host
      - APP_REDIS_PORT=6379
      - APP_MONGO_HOST=mongo_host
      - APP_MONGO_PORT=27017
    volumes:
      - "${SOURCE_DATA}/raw_data:/usr/share/raw_data"
      - "./data_client/app:/www/app"
    container_name: data-client
    ports:
      - "5001:5000"
    networks:
      - aviation_network

networks:
  aviation_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450